### ISSUE TITLE
how to construct the off-the-shelf networks?

### ISSUE THREAD

**Issue by mingminzhen** [Relja/netvlad#2]
i want to construct the off-the-shelf network:
caffe_offtheshelf_conv5_max.mat, vd16_offtheshelf_conv5_3_max.mat.
I try to do that as you suggest, but one question is that how to define the options since i find the example code in trainweakly.m:
   % ----- Network setup

```
net= loadNet(opts.netID, opts.layerName);

% --- Add my layers
net= addLayers(net, opts, dbTrain);
```

.
I do not know how to define the opts, dbTrain for addLayers.
Could you give me additional advice or upload the copy of source code about how to obtain the off-the-shelf networks?

**Comment by Relja** [comment]
Please check the readme, and our project page given in the paper.
Off-the-shelf networks are provided by MatConvNet on their website.

Regards,
Relja

**Comment by Relja** [comment]
I.e. here
http://www.vlfeat.org/matconvnet/pretrained/

**Comment by Relja** [comment]
And the opts you talk about are simple network name (i.e. if you see loadNet it takes caffe or vd16 as netID), while the other option is the name of the layer you want to crop the network to.
Please don't open issues for questions whose answers can be found in the Readme or Readme_more

**Comment by Relja** [comment]
Sorry, I just re-read your question and realized I didn't completely understand it in the first reading. However, it's still better to ask me these questions directly via email instead of opening an issue - it's not a bug with the code, just a question. Here is my answer:

To construct the max pooling networks (after you downloaded the off-the-shell networks from the MatConvNet website), you can simply do this:

```
net= load('imagenet-caffe-ref.mat'); net= vl_simplenn_tidy(net); % load
net= relja_cropToLayer(net, 'conv5'); % crop to a desired layer
net.layers{end+1}= layerTotalMaxPool(); % add a max pooling layer
net.layers{end+1}= layerWholeL2Normalize(); % add a L2 normalization layer
```

Or, if you want to use the above functions, specify the opts (they inherited from `trainWeakly` and as such are defined in README.md, README_more.md with respect to `trainWeakly`, and can be inferred from `demo.m` as well, as well as `loadNet.m`):

```
opts= {};
opts.netID= 'caffe'; % or 'vd16'
opts.layerName= 'conv5';
opts.method= 'max';
net= loadNet(opts.netID, opts.layerName);
net= addLayers(net, opts, []); % for max pooling you don't need dbTrain as there is no training at all, for vlad you need it as clustering needs to be performed (or load our clusters, downloadable at our project page http://www.di.ens.fr/willow/research/netvlad/ under `Initialization data`)
```

If you want to construct NetVLAD instead, you would use `opts.method= 'vlad_preL2_intra';` and construct the network with `net= addLayers(net, opts, dbTrain);` where details on how to load `dbTrain` are found in the README's (e.g. `dbTrain= dbPitts(false, 'train');` ). If you just want to use the provided cluster centres, then you don't even need to load dbTrain but do `dbTrain= struct('name', 'pitts30k_train');` as this provides the training dataset name which is sufficient to load the precomputed clusters.

**Comment by Relja** [comment]
P.S. The off-the-shelf networks with added layers (max, NetVLAD) are also downloadable from our research page ( http://www.di.ens.fr/willow/research/netvlad/ ), e.g.:
http://www.di.ens.fr/willow/research/netvlad/data/models/vd16_offtheshelf_conv5_3_max.mat

**Comment by mingminzhen** [comment]
thanks!
