### ISSUE TITLE
How to replace utm coordinates with GPS coordinates in my dataset?

### ISSUE THREAD

**Issue by zhanqan** [Relja/netvlad#23]
Can I use GPS coordinates in my dataset to replace the utm coordinates to generate .mat files ? Do I need to modify the code which is used to find closePosition?（db.cp= closePosition(db.utmDb, db.posDistThr);  in dbBase.m)
If I use GPS coordinates, do I need to modify the code to use a different radius, and a suitable distance measure?

**Comment by Relja** [comment]
UTM coordinates can be viewed as simply (x, y) coordinates on a plane in meters, it's a "flattening" of the Earth surface which can be considered flat in small regions. The point is that you can take Euclidean distance between UTM coordinates and get the approximate distance between two points on Earth in meters. You can easily convert GPS to UTM, there are free open libraries online for this.

If you want to use GPS instead, just ask yourself if Euclidean distance between GPS coordinates makes sense. I think it generally does but I am not an expert on this, as long as area covered is not too large (and I don't know what is "too large"), since GPS coordinates are essentially angles so you're approximating spherical distances with Euclidean distances (if the are is "large" this is bad, or if you are close to the poles etc).

Of course you need to change the threshold. The code assumes UTM coordinates so distances in meters, so the threshold is defined in meters. If you switch to GPS, distance won't be in meters. Distance of 15 in UTM means 15 meters, distance of 15 in longitude means 1/24 of the Earth's circumference.
