### ISSUE TITLE
the class layerWholeL2Normalize not have the attribute 'weights'

### ISSUE THREAD

**Issue by zongbingwang** [Relja/netvlad#3]
RT

**Comment by Relja** [comment]
Details please.
1) How to reproduce? What network, what version of MatConvNet?
2) Full error text / back trace

**Comment by zongbingwang** [comment]
Sorry for I did not give the details.
1. setting:
   NetVLAD: Version 1.03 (04 Mar 2016)
   relja_matlab: Version 1.02 (29 Feb 2016)
   MatConvNet: 1.0-beta20
2. Error:
   There are some errors when I use the function "relja_simplenn_tidy".
   
   Ther information:


```
    '''''''''''''''''''''''''''''''''''

    No public field weights exists for class layerWholeL2Normalize.

Error in vl_simplenn_tidy (line 51)
    layer.weights = {};

Error in relja_simplenn_tidy (line 25)
    net = vl_simplenn_tidy(net);

Error in test (line 21)
    net = relja_simplenn_tidy(net);

'''''''''''''''''''''''''''''''''''''''''''
```

3.Test Code:


```
% Set the MATLAB paths
setup;

% ---------- Use/test our networks

% Load our network
netID= 'vd16_tokyoTM_conv5_3_vlad_preL2_intra_white';
paths= localPaths();
load( sprintf('%s%s.mat', paths.ourCNNs, netID), 'net' );

a = sprintf('%s%s.mat', paths.ourCNNs, netID);
disp (a);
net= relja_simplenn_tidy(net);      //error
```

4.And I am new with MATLAB.. Thank you very much!!

**Comment by Relja** [comment]
The problem is due to the latest version of MatConvNet (1.0-beta20) which introduced an error, thanks for pointing this out.
I have raised this issue with the MatConvNet team ( https://github.com/vlfeat/matconvnet/issues/552 ) and am waiting to see what they do / how they fix it.

In the mean time, you have two options:

1) Use a slightly older version of MatConvNet (1.0-beta18 or 1.0-beta19)

2) Apply the following changes which seem to fix the problem:

a) in MatConvNet `matlab/simplenn/vl_simplenn_tidy.m` change line 50 `if ~isfield(layer, 'weights')` to `if ~isfield(layer, 'weights') && ~isprop(layer, 'weights')`, and line 106 `if ~isfield(layer, defaults{i})` to `if ~isfield(layer, defaults{i}) && ~isprop(layer, defaults{i})`

b) In NetVLAD code, add `weights= {}` to files `layerWholeL2Normalize.m`, `layerTotalAvg.m`, `layerTotalMax.m` just after the line `precious= false`

c) in NetVLAD code, file `netPrepareForTrain`, change line 6 `if i>=backPropToLayer && isFieldOrProp(net.layers{i}, 'weights')` to `if i>=backPropToLayer && isFieldOrProp(net.layers{i}, 'weights') && ~isempty(net.layers{i}.weights)`

**Comment by zongbingwang** [comment]
thank you very much！

**Comment by Relja** [comment]
The MatConvNet team has fixed the issue I referenced above (in patch https://github.com/vlfeat/matconvnet/commit/91399d47fcfcd06836f30ee3d88fcc7116ae40e0 ), so the NetVLAD code works without any modifications now.
