### ISSUE TITLE
About demo test

### ISSUE THREAD

**Issue by why-freedom** [Relja/netvlad#30]
When I run this code， I meet this problem， I dont konw why，hope your answer。thank you。

>> demoRetrieval
警告: 名称不存在或不是目录: E:\SLAM相关\回环检测\Code\matconvnet\matlab\mex 
> In path (line 109)
  In addpath (line 96)
  In vl_setupnn (line 13)
  In run (line 91)
  In setup (line 3)
  In demoRetrieval (line 11) 
警告: MatConvNet is not compiled. Consider running `vl_compilenn`. 
> In vl_setupnn (line 24)
  In run (line 91)
  In setup (line 3)
  In demoRetrieval (line 11) 
serialAllFeats: Start
serialAllFeats: Done
serialAllFeats: Start
serialAllFeats: Done
错误使用 fread
文件标识符无效。使用 fopen 生成有效的文件标识符。
出错 demoRetrieval (line 79)
dbFeat= fread( fopen(dbFeatFn, 'rb'), inf, 'float32=>single');

**Comment by Relja** [comment]
Your log says:
"MatConvNet is not compiled. Consider running vl_compilenn"
So it sounds like you haven't compiled MatConvNet. Please follow MatConvNet installation instructions: https://www.vlfeat.org/matconvnet/install/
After that, please remove the files created by your previous run as they are likely empty due to the errors, and the code doesn't redo files if they already exist.
