### ISSUE TITLE
yael_dummy error

### ISSUE THREAD

**Issue by WillTeng** [Relja/netvlad#32]
hello,when i run tiny tokyo time machine datasets,it show assert error in yael_nn file at line 4 and my plateform is window

**Comment by Relja** [comment]
This function searches for k nearest neighbour in a database of vectors. The assert states that the database size should be larger than k (otherwise it doesn't make sense). So I'm guessing something went wrong with feature extraction and you have an empty database. Do you have the actual Tokyo Time Machine images (if not the feature extraction will return empty)? If you need the place recognition datasets, please email me at relja@relja.fino.

**Comment by WillTeng** [comment]
I use Tiny subset of Tokyo Time Machine that contains 360 images,is that not work?

**Comment by Relja** [comment]
So you have the actual images? If yes, then it's strange this gives an error. Are you sure everything else worked fine without errors (i.e. you installed matconvnet and it works) ?

**Comment by WillTeng** [comment]
I just compile matconvnet again and test it,it works successfully

**Comment by Relja** [comment]
Good

**Comment by WillTeng** [comment]
I add an equal sign to the assert,it work normally.Is this data problem?or sometimes k can equal database size?

**Comment by Relja** [comment]
The function returns k nearest neighbours out of the database. You are forcing k to be the same as the database size.

**Comment by WillTeng** [comment]
not same,it is smaller or equal
